# Generated by Django 5.2.3 on 2025-06-19 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLaterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_SUBMISSION', 'Pending Submission'), ('SUBMITTED_KYC', 'KYC Submitted'), ('PENDING_CRC_CHECK', 'Pending Credit Check'), ('CRC_APPROVED', 'Credit Check Approved'), ('CRC_REJECTED', 'Credit Check Rejected'), ('APPROVED_ELIGIBLE', 'Approved for Pay Later'), ('REJECTED_INELIGIBLE', 'Rejected for Pay Later')], default='PENDING_SUBMISSION', help_text='Current status of the Pay Later application.', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(help_text="e.g., NIN, Driver's License number, Passport number.", max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, help_text='Credit score returned by CRC software.', null=True)),
                ('crc_decision_data', models.JSONField(blank=True, help_text='Raw JSON response from CRC software for auditing.', null=True)),
                ('approved_credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit approved by CRC/system.', max_digits=12, null=True)),
                ('is_eligible', models.BooleanField(default=False, help_text="Final decision on user's Pay Later eligibility.")),
                ('eligibility_reason', models.TextField(blank=True, help_text='Reason for approval or rejection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user submitting this application.', on_delete=django.db.models.deletion.CASCADE, related_name='pay_later_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pay Later Applications',
            },
        ),
    ]
