# Generated by Django 5.2.3 on 2025-06-19 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paylater', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('FULLY_REPAID', 'Fully Repaid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50)),
                ('delivery_address', models.TextField()),
                ('delivery_phone_number', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(choices=[('OUTRIGHT', 'Pay Outright'), ('PAY_LATER_40', 'Pay Later (40% upfront)'), ('PAY_LATER_0', 'Pay Later (0% upfront)')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, help_text='Reference from payment gateway for initial payment.', max_length=255, null=True)),
                ('instalment_paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid upfront for instalment option.', max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid for Pay Later.', max_digits=10)),
                ('repayment_due_date', models.DateField(blank=True, help_text='Date by which the remaining balance must be paid.', null=True)),
                ('pay_later_application', models.ForeignKey(blank=True, help_text='The approved Pay Later application used for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to='paylater.paylaterapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of product at time of order', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
